blank_issues_enabled: false
contact_links:
  - name: WordPress.org Support Forum
    url: https://wordpress.org/support/plugin/extra-product-data-for-woocommerce/
    about: Please ask usage questions here.