# This workflow updates the plugin assets and readme on the WordPress.org repository when changes are pushed to the update-readme branch.
name: Plugin asset/readme update
on:
  push:
    branches:
      - update-readme
jobs:
  trunk:
    if: github.repository == 'triopsi/extra-product-data-for-woocommerce'
    name: Push to trunk
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Plugin asset/readme update
      uses: tinify/action-wordpress-plugin-asset-update@stable
      env:
        SLUG: extra-product-data-for-woocommerce
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}